package com.example.myfirstapp

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "tasks")
class Task(
    @ColumnInfo(name = "sets") val sets: Int,
    @ColumnInfo(name = "reps") val reps: Int,
    @ColumnInfo(name = "tag") val tag: String,
    @ColumnInfo(name = "intensity") val intensity: Int,
    @ColumnInfo(name = "unit") val unit: String
) {
    // Use 0 as a default when creating the object or initializing the autogenerated key
    @PrimaryKey (autoGenerate = true) var tid: Int = 0
//    var tag: String = ""
//    var sets: Int = 0
//    var reps: Int = 0
//    var intensity: Int = 0
//    var unit: String = ""

    init {
//        this.sets = sets
//        this.reps = reps
//        this.tag = tag
//        this.intensity = intensity
//        this.unit = unit
    }

    override fun toString(): String {
        return "Sets = $sets\nReps = $reps\nTag = $tag\nIntensity = $intensity\nUnit = $unit\n"
    }
}